name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - master  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17 (needed for Spring Boot app)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build Spring Boot application using Maven
    - name: Build Spring Boot App with Maven
      run: mvn clean package -DskipTests

    # Step 4: Set up SSH key for EC2 access
    - name: Set up SSH key for EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" > ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config

    # Step 5: Copy the JAR file to EC2 instance
    - name: Copy JAR to EC2
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no target/*.jar ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/app.jar

    # Step 6: SSH into EC2 and start the application
    - name: SSH and deploy app to EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Stop any existing Spring Boot app
          sudo pkill -f 'java -jar' || true
          
          # Start the new app
          nohup java -jar /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &

          # Optionally tail the log
          tail -f /home/ubuntu/app.log
        EOF
